# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 00:38
from __future__ import unicode_literals

from django.db import migrations


def create_task_categories(apps, schema_editor):
    TaskCategory = apps.get_model('tasks', 'TaskCategory')

    TaskCategory.objects.bulk_create([
        TaskCategory(
            name='General',
            description='A task that needs to get done'
        ),
        TaskCategory(
            name='Bug',
            description='A problem that inhibits workflow of the product'
        ),
        TaskCategory(
            name='Enhancement',
            description='A feature that extends usability of the product'
        ),
        TaskCategory(
            name='Question',
            description='A custom issue that needs investigating'
        )
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_task_categories),
    ]
